version: '3.8'

services:
  backend:
    build: .
    container_name: innovatech-backend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - backend_data:/app/data

volumes:
  backend_data: